Update documentation according to the latest functions-framework
OpenFunction/samples pull request #39
Opened 2022-01-11 05:54 UTC by tpiperatgod

Signed-off-by: laminar <fangtian@kubesphere.io>

2022-01-11 06:06 UTC, benjaminhuo requested changes

2022-01-11 06:06 UTC, benjaminhuo commented on functions-framework/README.md
> +	r := preHookLogic(ctx.Ctx)
where to find code for preHookLogic?

2022-01-11 06:19 UTC, tpiperatgod commented on functions-framework/README.md
> +	r := preHookLogic(ctx.Ctx)
add the `preHookLogic()`

2022-01-11 08:42 UTC, benjaminhuo commented on functions-framework/golang/Async/README.md
> +## Context signature function
Context signature function => OpenFunction Function

2022-01-11 08:43 UTC, benjaminhuo commented on functions-framework/golang/Knative/README.md
> +## Http signature function
Http signature function
=>
Http Function

2022-01-11 08:43 UTC, benjaminhuo commented on functions-framework/golang/Knative/README.md
> +## CloudEvents signature function
CloudEvents signature function
=>
CloudEvents Function

2022-01-12 02:40 UTC, benjaminhuo approved these changes

2022-01-12 02:40 UTC, merged